#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache
title: Tizen Watch Apps DB
description: A guide to extend life of Tizen based smartwatches
